unstable_features = true
version = "Two"
newline_style = "Unix"
use_field_init_shorthand = true
fn_single_line = true
brace_style = "AlwaysNextLine"
control_brace_style ="ClosingNextLine"
format_strings = true
hard_tabs = true
wrap_comments = true
format_macro_matchers = true
format_macro_bodies = true
