[package]
name = "ly_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
state = "0.5.2"
crossbeam = "0.8.1"
parking_lot = "0.12.0"

ly_log = { path = "../ly_log" }
